routes/web.php
<?php

use App\Http\Controllers\CategoryRoomController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\FacilityController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\RoomImageController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
// Route::get('/test', [CustomerController::class, 'test1']);
// Route::post('/register-test', [CustomerController::class, 'testing'])->name('test');

Route::group(['middleware' => 'auth'], function() {
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::resource('category', CategoryRoomController::class);
    Route::group(['prefix' => 'category'], function() {
        Route::post('/update/{category}', [CategoryRoomController::class, 'update'])->name('category.update');
        Route::get('/destroy/{category}', [CategoryRoomController::class, 'destroy'])->name('category.destroy');
    });

    Route::resource('user', UserController::class);
    Route::group(['prefix' => 'user'], function() {
        Route::post('/update/{user}', [UserController::class, 'update'])->name('user.update');
        Route::get('/destroy/{user}', [UserController::class, 'destroy'])->name('user.destroy');
    });

    Route::resource('room', RoomController::class);
    Route::group(['prefix' => 'room'], function() {
        Route::post('/update/{room}', [RoomController::class, 'update'])->name('room.update');
        Route::get('/destroy/{room}', [RoomController::class, 'destroy'])->name('room.destroy');
    });

    Route::resource('customer', CustomerController::class);
    Route::group(['prefix' => 'customer'], function() {
        Route::post('/update/{customer}', [CustomerController::class, 'update'])->name('customer.update');
        Route::get('/destroy/{customer}', [CustomerController::class, 'destroy'])->name('customer.destroy');
    });

    Route::resource('facility', FacilityController::class);
    Route::group(['prefix' => 'facility'], function() {
        Route::post('/update/{facility}', [FacilityController::class, 'update'])->name('facility.update');
        Route::get('/destroy/{facility}', [FacilityController::class, 'destroy'])->name('facility.destroy');
    });

    Route::resource('order', OrderController::class);
    Route::group(['prefix' => 'order'], function() {
        Route::post('/update/{order}', [OrderController::class, 'update'])->name('order.update');
        Route::get('/invoice/{id}/print', [OrderController::class, 'print'])->name('order.print');
    });
});

resources/views/admin/category/index.blade.php
@extends('layouts.app')

@section('title')
    <title>Category</title>
@endsection

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Category</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Category</a></li>
                            <li class="breadcrumb-item active">Index</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        @if (session()->has('success'))
                            <div class="alert alert-success">
                                {{ session()->get('success') }}
                            </div>
                        @endif
                        <div class="card">
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title p-3">Table Category</h3>
                                    <div class="card-tools p-3">
                                        <a href="{{ route('category.create') }}"
                                            class="d-relative btn ms-auto btn btn-primary">Create Data</a>
                                    </div>
                                </div>
                                <!-- /.card-header -->
                                <div class="card-body">
                                    <table id="example1" class="table table-bordered table-striped">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>Gambar</th>
                                                <th>Nama</th>
                                                <th>Harga</th>
                                                <th>Luas</th>
                                                <th>Kapasistas</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach ($category as $item)
                                                <tr>
                                                    <td>{{ $loop->iteration }}</td>
                                                    <td><img src="{{ asset('storage/room/image/' . $item->url_image) }}"
                                                            alt="..." style="width: 50%"
                                                            class="img-fluid img-thumbnail"></td>
                                                    <td>{{ $item->name }}</td>
                                                    <td>{{ $item->price }}
                                                    </td>
                                                    <td>{{ $item->wide }}</td>
                                                    <td>{{ $item->capacity }}</td>
                                                    <td>
                                                        <a href="{{ route('category.edit', ['category' => $item->id]) }}"
                                                            class="btn btn-primary "><i class="fa fa-edit"></i> Edit</a>
                                                        <a href="{{ route('category.destroy', ['category' => $item->id]) }}"
                                                            onclick="return confirmDelete()" class="btn btn-danger "><i
                                                                class="fa fa-trash"></i> Delete</a>
                                                    </td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.row -->
                </div>
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('script')
    <script>
        $(function() {
            $("#example1").DataTable({
                "responsive": true,
                "lengthChange": false,
                "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
    <script>
        function confirmDelete() {
            return confirm('Apakah Anda yakin ingin menghapus data ini?');
        }
    </script>
@endsection

resources/views/admin/category/manage.blade.php
@extends('layouts.app')

@section('title')
    <title>Manage Category</title>
@endsection

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Manage Category</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Category</a></li>
              <li class="breadcrumb-item active">Manage</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
              <div class="col-12">
                @if(session()->has('error'))
                    <div class="alert alert-danger">
                        {{ session()->get('error') }}
                    </div>
                @endif
                <div class="card card-primary">
                    {{-- <div class="card-header">
                      <h3 class="card-title">Quick Example</h3>
                    </div> --}}
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form method="POST" action="{{ !empty($category) ? route('category.update', ['category' => $category->id]) : route('category.store') }}" enctype="multipart/form-data">
                        {{ csrf_field() }}
                      <div class="card-body">
                        <div class="form-group">
                          <label for="name">Category Name</label>
                          <input type="text" class="form-control" name="name" id="name" placeholder="Category Name" value="{{ old('name', @$category->name) }}">
                        </div>
                        <div class="form-group">
                          <label for="price">Price</label>
                          <input  class="form-control" name="price" id="price" type="number" placeholder="Price" value="{{ old('price', @$category->price) }}">
                        </div>
                        <div class="form-group">
                            <label for="wide">Wide</label>
                            <input class="form-control" name="wide" id="wide" placeholder="Wide Room" value="{{ old('wide', @$category->wide) }}">
                        </div>
                        <div class="form-group">
                            <label for="capacity">Capacity</label>
                            <input class="form-control" name="capacity" id="capacity" type="number" placeholder="Capacity Room" value="{{ old('capacity', @$category->capacity) }}">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputFile">Upload Image</label>
                            <div class="input-group">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" name="url_image" id="customFile">
                                    <label class="custom-file-label" for="customFile">Choose file</label>
                                </div>
                            </div>
                          </div>
                        {{-- <div class="form-group">
                          <label for="exampleInputFile">File input</label>
                          <div class="input-group">
                            <div class="custom-file">
                              <input type="file" class="custom-file-input" id="exampleInputFile">
                              <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                            </div>
                            <div class="input-group-append">
                              <span class="input-group-text">Upload</span>
                            </div>
                          </div>
                        </div> --}}
                      </div>
                      <!-- /.card-body -->

                      <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                      </div>
                    </form>
                  </div>
            </div>
            <!-- /.row -->
          </div>
    </section>
    <!-- /.content -->
  </div>
@endsection

@section('script')
<script>
    $(function () {
      $("#example1").DataTable({
        "responsive": true, "lengthChange": false, "autoWidth": false,
        "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
      }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
  </script>
@endsection