routes/web.php
<?php

use App\Http\Controllers\CategoryRoomController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\FacilityController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\RoomImageController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
// Route::get('/test', [CustomerController::class, 'test1']);
// Route::post('/register-test', [CustomerController::class, 'testing'])->name('test');

Route::group(['middleware' => 'auth'], function() {
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::resource('category', CategoryRoomController::class);
    Route::group(['prefix' => 'category'], function() {
        Route::post('/update/{category}', [CategoryRoomController::class, 'update'])->name('category.update');
        Route::get('/destroy/{category}', [CategoryRoomController::class, 'destroy'])->name('category.destroy');
    });

    Route::resource('user', UserController::class);
    Route::group(['prefix' => 'user'], function() {
        Route::post('/update/{user}', [UserController::class, 'update'])->name('user.update');
        Route::get('/destroy/{user}', [UserController::class, 'destroy'])->name('user.destroy');
    });

    Route::resource('room', RoomController::class);
    Route::group(['prefix' => 'room'], function() {
        Route::post('/update/{room}', [RoomController::class, 'update'])->name('room.update');
        Route::get('/destroy/{room}', [RoomController::class, 'destroy'])->name('room.destroy');
    });

    Route::resource('customer', CustomerController::class);
    Route::group(['prefix' => 'customer'], function() {
        Route::post('/update/{customer}', [CustomerController::class, 'update'])->name('customer.update');
        Route::get('/destroy/{customer}', [CustomerController::class, 'destroy'])->name('customer.destroy');
    });

    Route::resource('facility', FacilityController::class);
    Route::group(['prefix' => 'facility'], function() {
        Route::post('/update/{facility}', [FacilityController::class, 'update'])->name('facility.update');
        Route::get('/destroy/{facility}', [FacilityController::class, 'destroy'])->name('facility.destroy');
    });

    Route::resource('order', OrderController::class);
    Route::group(['prefix' => 'order'], function() {
        Route::post('/update/{order}', [OrderController::class, 'update'])->name('order.update');
        Route::get('/invoice/{id}/print', [OrderController::class, 'print'])->name('order.print');
    });
});

app/Models/Room.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Room extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'room';

    protected $fillable = [
        'room_category_id','room_number','status'
    ];

    public function roomCategory()
    {
        return $this->belongsTo(CategoryRoom::class, 'room_category_id', 'id');
    }

    public function orderDetail()
    {
        return $this->hasOne(OrderDetail::class, 'room_id', 'id');
    }


}

app/Http/Controllers/API/RoomController.php
<?php

namespace App\Http\Controllers\API;

use App\Helpers\ResponseFormatter;
use App\Http\Controllers\Controller;
use App\Models\CategoryRoom;
use App\Models\Room;
use App\Models\RoomImage;
use Illuminate\Http\Request;

class RoomController extends Controller
{
    public function indexRoom()
    {
        $room = Room::with(['roomCategory','roomImage'])
        ->get();

        if($room)
            return ResponseFormatter::success(
                $room,
                'Room data retrieved successfully'
            );
        else
            return ResponseFormatter::error(
                null,
                'Room data not exist',
                404,
            );

    }

    public function indexCategory()
    {
        $category = CategoryRoom::with(['room','facility'])
        ->get();

        if($category)
            return ResponseFormatter::success(
                $category,
                'Room Category data retrieved successfully'
            );
        else
            return ResponseFormatter::error(
                null,
                'Room data not exist',
                404,
            );

    }

    public function indexImage()
    {
        $images = RoomImage::with(['room'])
        ->get();

        if($images)
            return ResponseFormatter::success(
                $images,
                'Room Image data retrieved successfully'
            );
        else
            return ResponseFormatter::error(
                null,
                'Room Image data not exist',
                404,
            );
    }
}

app/Http/Controllers/RoomController.php
<?php

namespace App\Http\Controllers;

use App\Models\CategoryRoom;
use App\Models\Room;
use Exception;
use Illuminate\Http\Request;

class RoomController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $room = Room::all();

        return view('admin.room.index', compact('room'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = CategoryRoom::all();

        return view('admin.room.manage', compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $this->validate($request,[
                'room_category_id' => ['required'],
                'room_number' => ['required','unique:room,room_number'],
                'status' => ['required'],
            ]);

            $data = $request->except('_data');

            Room::create($data);

            return redirect()->route('room.index')->with('success', 'Success Create Kamar');
        } catch (Exception $error) {
            return redirect()->back()->with('error', $error->validator->errors());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $room = Room::findorFail($id);
        $category = CategoryRoom::all();

        $data = array(
            'room' => $room,
            'category' => $category,
        );

        return view('admin.room.manage', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $this->validate($request,[
                'room_category_id' => ['required'],
                'room_number' => ['required','unique:room,room_number,'.$id],
                'status' => ['required'],
            ]);

            $room = Room::findorFail($id);
            $data = $request->except('_data');

            $room->update($data);

            return redirect()->route('room.index')->with('success', 'Success Update Kamar');
        } catch (Exception $error) {
            return redirect()->back()->with('error', $error->validator->errors());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $room = Room::findorFail($id);
        $room->status = 'not available';
        $room->update();

        $room->delete();

        return redirect()->route('room.index')->with('success', 'Success Delete Kamar');
    }
}

resources/views/admin/room/index.blade.php
@extends('layouts.app')

@section('title')
    <title>Room</title>
@endsection

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Room</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Room</a></li>
                            <li class="breadcrumb-item active">Index</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        @if (session()->has('success'))
                            <div class="alert alert-success">
                                {{ session()->get('success') }}
                            </div>
                        @endif
                        <div class="card">
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title p-3">Table Room</h3>
                                    <div class="card-tools p-3">
                                        <a href="{{ route('room.create') }}"
                                            class="d-relative btn ms-auto btn btn-primary">Create Data</a>
                                    </div>
                                </div>
                                <!-- /.card-header -->
                                <div class="card-body">
                                    <table id="example1" class="table table-bordered table-striped">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>No Kamar</th>
                                                <th>Kategori</th>
                                                <th>Status</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach ($room as $item)
                                                <tr>
                                                    <td>{{ $loop->iteration }}</td>
                                                    <td>{{ $item->room_number }}</td>
                                                    <td>{{ $item->roomCategory->name }}
                                                    </td>
                                                    <td>{{ $item->status }}</td>
                                                    <td>
                                                        <a href="{{ route('room.edit', ['room' => $item->id]) }}"
                                                            class="btn btn-primary "><i class="fa fa-edit"></i> Edit</a>
                                                        <a href="{{ route('room.destroy', ['room' => $item->id]) }}"
                                                            class="btn btn-danger " onclick="return confirmDelete()"><i
                                                                class="fa fa-trash"></i> Delete</a>
                                                    </td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.row -->
                </div>
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('script')
    <script>
        $(function() {
            $("#example1").DataTable({
                "responsive": true,
                "lengthChange": false,
                "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
    <script>
        function confirmDelete() {
            return confirm('Apakah Anda yakin ingin menghapus data ini?');
        }
    </script>
@endsection

resources/views/admin/room/manage.blade.php
@extends('layouts.app')

@section('title')
    <title>Manage Room</title>
@endsection

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Manage Room</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Room</a></li>
              <li class="breadcrumb-item active">Manage</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
              <div class="col-12">
                @if(session()->has('error'))
                    <div class="alert alert-danger">
                        {{ session()->get('error') }}
                    </div>
                @endif
                <div class="card card-primary">
                    {{-- <div class="card-header">
                      <h3 class="card-title">Quick Example</h3>
                    </div> --}}
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form method="POST" action="{{ !empty($room) ? route('room.update', ['room' => $room->id]) : route('room.store') }}">
                        {{ csrf_field() }}
                      <div class="card-body">
                        <div class="form-group">
                            <label for="category">Kategori Kamar</label>
                            <select class="form-control" id="category" name="room_category_id">
                                @foreach ($category as $item)
                                <option value="{{ $item->id }}" {{ old('room_category_id', @$item->id == @$room->room_category_id ? 'selected' : '') }}>{{ $item->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                          <label for="room_number">Nomor Kamar</label>
                          <input type="text" class="form-control" name="room_number" id="room_number" placeholder="Nomor Kamar" value="{{ old('room_number', @$room->room_number) }}">
                        </div>
                        <div class="form-group">
                            <label for="status">Status</label>
                            <select class="form-control" id="status" name="status">
                                <option value="Available" {{ old('status', @$room->status == 'Available' ? 'selected' : '') }}>Available</option>
                                <option value="Not Available" {{ old('status', @$room->status == 'Not Available' ? 'selected' : '') }}>Not Available</option>
                            </select>
                        </div>
                      </div>

                      {{-- <div class="form-group">
                        <label for="jabatan">Select</label>
                        <select class="form-control">
                          <option>option 1</option>
                          <option>option 2</option>
                          <option>option 3</option>
                          <option>option 4</option>
                          <option>option 5</option>
                        </select>
                      </div> --}}
                      <!-- /.card-body -->

                      <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                      </div>
                    </form>
                  </div>
            </div>
            <!-- /.row -->
          </div>
    </section>
    <!-- /.content -->
  </div>
@endsection

@section('script')
<script>
    $(function () {
      $("#example1").DataTable({
        "responsive": true, "lengthChange": false, "autoWidth": false,
        "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
      }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
  </script>
@endsection