routes/web.php
<?php

use App\Http\Controllers\CategoryRoomController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\FacilityController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\RoomImageController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
// Route::get('/test', [CustomerController::class, 'test1']);
// Route::post('/register-test', [CustomerController::class, 'testing'])->name('test');

Route::group(['middleware' => 'auth'], function() {
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::resource('category', CategoryRoomController::class);
    Route::group(['prefix' => 'category'], function() {
        Route::post('/update/{category}', [CategoryRoomController::class, 'update'])->name('category.update');
        Route::get('/destroy/{category}', [CategoryRoomController::class, 'destroy'])->name('category.destroy');
    });

    Route::resource('user', UserController::class);
    Route::group(['prefix' => 'user'], function() {
        Route::post('/update/{user}', [UserController::class, 'update'])->name('user.update');
        Route::get('/destroy/{user}', [UserController::class, 'destroy'])->name('user.destroy');
    });

    Route::resource('room', RoomController::class);
    Route::group(['prefix' => 'room'], function() {
        Route::post('/update/{room}', [RoomController::class, 'update'])->name('room.update');
        Route::get('/destroy/{room}', [RoomController::class, 'destroy'])->name('room.destroy');
    });

    Route::resource('customer', CustomerController::class);
    Route::group(['prefix' => 'customer'], function() {
        Route::post('/update/{customer}', [CustomerController::class, 'update'])->name('customer.update');
        Route::get('/destroy/{customer}', [CustomerController::class, 'destroy'])->name('customer.destroy');
    });

    Route::resource('facility', FacilityController::class);
    Route::group(['prefix' => 'facility'], function() {
        Route::post('/update/{facility}', [FacilityController::class, 'update'])->name('facility.update');
        Route::get('/destroy/{facility}', [FacilityController::class, 'destroy'])->name('facility.destroy');
    });

    Route::resource('order', OrderController::class);
    Route::group(['prefix' => 'order'], function() {
        Route::post('/update/{order}', [OrderController::class, 'update'])->name('order.update');
        Route::get('/invoice/{id}/print', [OrderController::class, 'print'])->name('order.print');
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'address',
        'phone_number',
        'position',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = User::all();

        return view('admin.user.index', compact('user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.manage');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $this->validate($request,[
                'name' => ['required'],
                'email' => ['required','email'],
                'phone_number' => ['required','numeric'],
                'position' => ['required'],
                'address' => ['required'],
                // 'password' => ['required'],
            ]);

            $data = $request->except('_token');
            $data['password'] = bcrypt($data['password']);
            // dd($data);

            User::create($data);

            return redirect()->route('user.index')->with('success', 'Success Create Pegawai');
        } catch (\Throwable $th) {
            return redirect()->back()->with('error', 'There something wrong with your input');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findorFail($id);

        return view('admin.user.manage', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $this->validate($request,[
                'name' => ['required'],
                'email' => ['required','email'],
                'phone_number' => ['required','numeric'],
                'position' => ['required'],
                // 'password' => ['required'],
                'address' => ['required'],
            ]);

            $user = User::findorFail($id);

            $data = $request->except('_token');
            $data['password'] = bcrypt($data['password']);

            $user->update($data);

            return redirect()->route('user.index')->with('success', 'Success Edit Pegawai');
        } catch (\Throwable $th) {
            return redirect()->back()->with('error', 'There something wrong with your input');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findorFail($id);

        $user->delete();

        return redirect()->route('user.index')->with('success', 'Success Delete Pegawai');
    }
}

resources/views/admin/user/index.blade.php
@extends('layouts.app')

@section('title')
    <title>User</title>
@endsection

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Pegawai</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Pegawai</a></li>
              <li class="breadcrumb-item active">Index</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
              <div class="col-12">
                @if(session()->has('success'))
                    <div class="alert alert-success">
                        {{ session()->get('success') }}
                    </div>
                @endif
                <div class="card">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title p-3">Table Pegawai</h3>
                            <div class="card-tools p-3">
                                <a href="{{ route('user.create') }}" class="d-relative btn ms-auto btn btn-primary">Create Data</a>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Nama</th>
                                <th>Email</th>
                                <th>Alamat</th>
                                <th>Jabatan</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                                @foreach ($user as $item)
                                <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $item->name }}</td>
                                <td>{{ $item->email }}
                                </td>
                                <td>{{$item->address}}</td>
                                <td>{{ $item->position }}</td>
                                <td>
                                    <a href="{{ route('user.edit', ['user' => $item->id]) }}" class="btn btn-primary "><i class="fa fa-edit"></i> Edit</a>
                                    <a href="{{ route('user.destroy', ['user' => $item->id]) }}" class="btn btn-danger "><i class="fa fa-trash"></i> Delete</a>
                                </td>
                                </tr>
                                @endforeach
                            </tbody>
                            </table>
                        </div>
                    </div>
              </div>
            </div>
            <!-- /.row -->
          </div>
    </section>
    <!-- /.content -->
  </div>
@endsection

@section('script')
<script>
    $(function () {
      $("#example1").DataTable({
        "responsive": true, "lengthChange": false, "autoWidth": false,
        "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
      }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
  </script>
@endsection

resources/views/admin/user/manage.blade.php
@extends('layouts.app')

@section('title')
    <title>Manage User</title>
@endsection

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Manage Pegawai</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Pegawai</a></li>
              <li class="breadcrumb-item active">Manage</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
              <div class="col-12">
                @if(session()->has('error'))
                    <div class="alert alert-danger">
                        {{ session()->get('error') }}
                    </div>
                @endif
                <div class="card card-primary">
                    {{-- <div class="card-header">
                      <h3 class="card-title">Quick Example</h3>
                    </div> --}}
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form method="POST" action="{{ !empty($user) ? route('user.update', ['user' => $user->id]) : route('user.store') }}">
                        {{ csrf_field() }}
                      <div class="card-body">
                        <div class="form-group">
                          <label for="name">Nama</label>
                          <input type="text" class="form-control" name="name" id="name" placeholder="Nama Pegawai" value="{{ old('name', @$user->name) }}">
                        </div>
                        <div class="form-group">
                          <label for="email">Email</label>
                          <input type="email" class="form-control" name="email" id="email" placeholder="email" value="{{ old('email', @$user->email) }}">
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" class="form-control" name="password" id="password">
                        </div>
                        <div class="form-group">
                            <label for="phone_number">No Handphone</label>
                            <input type="number" class="form-control" name="phone_number" id="phone_number" placeholder="No Handphone" value="{{ old('phone_number', @$user->phone_number) }}">
                        </div>
                        <div class="form-group">
                            <label for="capacity">Alamat</label>
                            <textarea name="address" id="" cols="30" rows="10" class="form-control">{{ old('address',@$user->address) }}</textarea>
                        </div>
                        <div class="form-group">
                            <label for="position">Jabatan</label>
                            <input type="text" class="form-control" name="position" id="position" placeholder="Position" value="{{ old('position', @$user->position) }}">
                        </div>
                      </div>
                      {{-- <div class="form-group">
                        <label for="jabatan">Select</label>
                        <select class="form-control">
                          <option>option 1</option>
                          <option>option 2</option>
                          <option>option 3</option>
                          <option>option 4</option>
                          <option>option 5</option>
                        </select>
                      </div> --}}
                      <!-- /.card-body -->

                      <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                      </div>
                    </form>
                  </div>
            </div>
            <!-- /.row -->
          </div>
    </section>
    <!-- /.content -->
  </div>
@endsection

@section('script')
<script>
    $(function () {
      $("#example1").DataTable({
        "responsive": true, "lengthChange": false, "autoWidth": false,
        "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
      }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
  </script>
@endsection